language: python

python:
  - "3.8"
  - "3.7"
  - "3.6"

cache: pip

script:
# basic install (no requirements)
  - pip install --no-deps . &&
    python -c "import bussilab" &&
    bussilab -h
  - pip uninstall --yes bussilab
# full install (with requirements)
  - pip install --upgrade . &&
    bussilab check --import
# run test suite
  - pip install --upgrade pytest pytest-cov &&
    PYTHONPATH=. py.test --cov=./
# pyflakes
  - pip install --upgrade pyflakes &&
    pyflakes bussilab
# mypy
  - pip install --upgrade mypy &&
    mypy bussilab
# pylint (ignore, too many false positives)
  - pip install --upgrade pylint &&
    pylint bussilab || echo ignore
# build doc
  - pip install --upgrade pdoc3 &&
    pdoc3 -f --html -o doc/ bussilab

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - pip install twine
  - if [ "${TRAVIS_JOB_NAME#*.}" = 1 ] ; then .travis/pushdoc ; fi

# TODO:
# - upload tags to pypi
# - upload doc somewhere
# - configure LGTM
