jobs:
  include:
    - name: python3.8
      language: python
      python: "3.8"
    - name: python3.7
      language: python
      python: "3.7"
    - name: python3.6
      language: python
      python: "3.6"
    - name: conda
    - name: conda-osx
      os: osx
    - name: macports
      os: osx

script:
# basic install (no requirements)
  - if [[ "$TRAVIS_JOB_NAME" =~ ^python ]] ; then
      pip install --no-deps . &&
      python -c "import bussilab" &&
      bussilab -h &&
      pip uninstall --yes bussilab ;
    fi

# full install (with requirements)
  - if [[ "$TRAVIS_JOB_NAME" =~ ^python ]] ; then
      pip install --upgrade . ;
    elif [[ "$TRAVIS_JOB_NAME" =~ ^conda ]] ; then
       curl -LO https://raw.githubusercontent.com/GiovanniBussi/conda-ci/master/conda-ci &&
       source ./conda-ci install &&
       source ./conda-ci install-conda-build &&
       export CPU_COUNT=4 &&
       if [ -n "$TRAVIS_TAG" ] ; then
         export VERSION="${TRAVIS_TAG#v}" ; 
       else
         export VERSION="0.0" ; 
       fi &&
       conda-build -c conda-forge conda &&
       conda install -c conda-forge -c local py-bussilab ;
    elif [[ "$TRAVIS_JOB_NAME" =~ ^macports ]] ; then
        curl -LO https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci &&
        source ./macports-ci install &&
        sudo port install python38 &&
        sudo port select --set python python38 &&
        sudo port install py-pip py-setuptools &&
        sudo port install py-argcomplete py-numba py-numpy py-scipy py-slackclient py-yaml &&
        sudo port select --set pip pip38 &&
        pip install --user --no-deps . &&
        PATH="$(python -c 'import site; print(site.USER_BASE + "/bin")'):$PATH" ;
    fi

# check if module can be imported
  - bussilab check --import ;

# install packages needed for testing
  - if [[ "$TRAVIS_JOB_NAME" =~ ^python ]] ; then
      pip install --upgrade pytest pytest-cov ;
    elif [[ "$TRAVIS_JOB_NAME" =~ ^conda ]] ; then
      conda install -c conda-forge pytest pytest-cov ;
    elif [[ "$TRAVIS_JOB_NAME" =~ ^macports ]] ; then
      sudo port install py-pytest py-pytest-cov &&
      sudo port select --set pytest pytest38 ;
    fi

# run test suite
  - pytest

# run test suite with coverage
  - PYTHONPATH=. pytest --cov=./

# the following checks and the manual building are only done in the python jobs on linux
  - if [[ "$TRAVIS_JOB_NAME" =~ ^python ]] ; then
      pip install --upgrade pyflakes mypy pylint pdoc3 jupyter nbconvert ;
    fi

# pyflakes
  - if [[ "$TRAVIS_JOB_NAME" =~ ^python ]] ; then
        pyflakes bussilab
    fi

# mypy
  - if [[ "$TRAVIS_JOB_NAME" =~ ^python ]] ; then
        mypy bussilab ;
    fi

# pylint (ignore, too many false positives)
  - if [[ "$TRAVIS_JOB_NAME" =~ ^python ]] ; then
        pylint bussilab || echo ignore ;
    fi

# build doc
  - if [[ "$TRAVIS_JOB_NAME" =~ ^python ]] ; then
        pdoc3 -f --html -o doc/ bussilab &&
        ( cd examples && ./render.sh ) &&
        mkdir doc/examples &&
        cp examples/*html doc/examples/ &&
        ( sudo apt-get install tree && cd doc/examples && tree -H '.' -L 1 --noreport --charset utf-8 > index.html ) ;
    fi

# fail if tag is inconsistent with version
  - if [ -n "$TRAVIS_TAG" ] ; then test v$(bussilab --version) == "$TRAVIS_TAG" ; fi

after_success:
  - if [ "${TRAVIS_JOB_NAME}" = python3.8 ] && [ "$TRAVIS_BRANCH" = master ] ; then .travis/pushdoc ; fi
  - if [ "${TRAVIS_JOB_NAME}" = python3.8 ] && [ -n "$TRAVIS_TAG" ] ; then
        pip install twine &&
        python setup.py sdist &&
        python -m twine upload -u bussilabbot -p "$BUSSILABBOT_PYPI" dist/bussilab-*.tar.gz ;
    fi
  - if [[ "${TRAVIS_JOB_NAME}" =~ ^conda ]] && [ -n "$TRAVIS_TAG" ] ; then
        anaconda -t $CONDA_UPLOAD_TOKEN upload -u bussilab -l main $CONDA_PREFIX/conda-bld/$TRAVIS_OS_NAME-64/py-bussilab*.tar.bz2 --force ;
    fi
  - bash <(curl -s https://codecov.io/bash)
