CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.13.sdk   # [osx and x86_64]
  - /opt/MacOSX11.0.sdk   # [osx and arm64]
python:
    - "3.13"
    - "3.12"
    - "3.11"
    - "3.10"
    - "3.9"
    - "3.8"
    - "3.7"
