{% set version = environ['VERSION'] %}

package:
  name: py-bussilab
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  skip: True  # [win or py2k]

requirements:
  host:
    - python
    - pip
  run:
    - argcomplete
    - numba
    - numpy
    - scipy
    - slackclient>=2
    - pyyaml
    - python

test:
  imports:
    - bussilab
  commands:
    - bussilab check --import

about:
  home: https://github.com/bussilab/py-bussilab
  license: LGPL-2.1
  license_family: GPL
  summary: 'A package collecting a heterogeneous set of tools.'
  description: |
    This package collects a number of tools that are useful enough to be distributed
    but too small to deserve being published as separate packages.
  doc_url: https://bussilab.github.io/doc-py-bussilab
  dev_url: https://github.com/bussilab/py-bussilab

extra:
  recipe-maintainers:
    - GiovanniBussi
