
name: CI

on:
  push:
  pull_request:

jobs:
  python:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        export BUSSILAB_TEST_NOTIFY_TOKEN="${{ secrets.BUSSILAB_TEST_NOTIFY_TOKEN }}"
        export BUSSILAB_TEST_NOTIFY_CHANNEL="${{ secrets.BUSSILAB_TEST_NOTIFY_CHANNEL }}"
        pytest -v

  macports:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install MacPorts
      run: |
        curl -LO https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci
        source ./macports-ci install
    - name: Install package
      run: |
        sudo port install python38 py38-pip py38-setuptools
        pip-3.8 install --user --no-deps .
        PATH="$(python3.8 -c 'import site; print(site.USER_BASE + "/bin")'):$PATH"
        sudo port install $(bussilab required --macports --pyver 38)
    - name : Run tests
      run: |
        PATH="$(python3.8 -c 'import site; print(site.USER_BASE + "/bin")'):$PATH"
        bussilab check --import
        sudo port install py38-pytest
        # ignore BUSSILAB_TEST_NOTIFY_TOKEN since it does not work with macports for some reason
        pytest-3.8 -v
